print("this is epic")
print("thats all volks")
#print("never seen footage")
print("now its time for maths yahhhyeeet")
print("i didnt know it works like this", 67-34+12)
print("the result should be 15 not 5", 20-10/2)
print("now i know that modulo is similar to restrechnung in geman")
print(4+5<3+3)
print(9>6)
print(6<6)
print(66%12, "if i am not stupid it should be 6")
